name: 'Lerna Graph'
description: 'Generate a graph of the lerna packages and version'
icon: book
color: purple
author: 'Tally Barak'
inputs:
  rootPath: 
    required: false
    description: 'Lerna rootPath'
    default: process.cwd()
  imagePath: 
    required: true
    description: 'Path for the image generated'
    default: 'lerna.png'

runs:
  using: 'node12'
  main: 'dist/index.js'
